import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { categoryDownload, categoryImage, categoryName, guideFor, knowledgeConfig, knowledgeKeys, knowledgeVerticals, relatedGuides } from "../../../knowledge/data";
import { KnowledgeFooter, KnowledgeHeader, KnowledgeMobileBar } from "../../../knowledge/KnowledgeSiteShell";
import { KnowledgeVisual } from "../../../knowledge/KnowledgeVisual";

export function generateStaticParams() { return knowledgeKeys.flatMap((vertical) => knowledgeVerticals[vertical].guides.map((guide) => ({ vertical, slug: guide.slug }))); }
export async function generateMetadata({params}:{params:Promise<{vertical:string;slug:string}>}):Promise<Metadata>{const{vertical,slug}=await params;const config=knowledgeConfig(vertical);const guide=config?guideFor(config,slug):null;if(!config||!guide)return{};const image=categoryImage(config,guide.category);return{title:guide.title,description:guide.description,alternates:{canonical:`https://unitedcontainerdepot.com/${config.key}/guides/${guide.slug}`},openGraph:{title:guide.title,description:guide.description,images:[image.src]}};}

const flowMap:Record<string,[string,string,string]>={buying:["Define need","Compare scope","Verify unit"],placement:["Measure route","Confirm site","Approve delivery"],equipment:["Measure item","Plan handling","Verify fit"],inputs:["Read requirements","Measure conditions","Control exposure"],safety:["Identify product","Apply rules","Document approval"],security:["Deter","Control access","Close out"],compliance:["Identify authority","Confirm rule","Keep record"],operations:["Assign owner","Inspect","Correct"],inventory:["Label","Place","Reconcile"],climate:["Measure","Select control","Monitor"],economics:["Acquire","Operate","Exit"],"fit-access":["Measure vehicle","Measure unit","Test path"],preservation:["Set limits","Control environment","Inspect"],recreation:["Group gear","Rate storage","Rotate"],modifications:["Define need","Qualified design","Inspect work"],ownership:["Approve site","Model cost","Plan exit"]};

export default async function KnowledgeGuidePage({params}:{params:Promise<{vertical:string;slug:string}>}){const{vertical,slug}=await params;const config=knowledgeConfig(vertical);const guide=config?guideFor(config,slug):null;if(!config||!guide)notFound();const image=categoryImage(config,guide.category);const download=categoryDownload(config,guide.category);const related=relatedGuides(config,guide);const steps=flowMap[guide.category]??flowMap.operations;const url=`https://unitedcontainerdepot.com/${config.key}/guides/${guide.slug}`;const schema={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:guide.title,description:guide.description,image:`https://unitedcontainerdepot.com${image.src}`,dateModified:"2026-07-18",author:{"@type":"Organization",name:"United Container Depot"},publisher:{"@type":"Organization",name:"United Container Depot"},mainEntityOfPage:url,about:config.context},{"@type":"FAQPage",mainEntity:guide.faq.map((item)=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))}]};return <main className="guide-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><KnowledgeHeader config={config}/><div className="guide-topbar guide-article-topbar"><div className="wrap"><Link href={`/${config.key}`}>{config.name} containers</Link><span>/</span><Link href={`/${config.key}/resources`}>Resource center</Link><span>/</span><b>{guide.navTitle}</b></div></div>
  <header className="guide-hero guide-hero-visual"><div className="wrap guide-hero-grid"><div className="guide-hero-copy"><span className="guide-category">{categoryName(config,guide.category)}</span><h1>{guide.title}</h1><p>{guide.description}</p><aside className="guide-answer"><span>Quick answer</span><p>{guide.quickAnswer}</p><a href="#field-notes">Go to field notes ↓</a></aside><div className="guide-meta"><span>UCD field guide</span><span>Exact-unit verification built in</span><span>Updated July 2026</span></div></div><figure className="guide-hero-media"><Image src={image.src} alt={image.alt} fill priority sizes="(max-width:800px) 100vw,44vw"/><figcaption>{config.name} field reference</figcaption><div className="guide-stat-row"><div><strong>01</strong><span>Define need</span></div><div><strong>02</strong><span>Verify site</span></div><div><strong>03</strong><span>Confirm unit</span></div></div></figure></div></header>
  <div className="wrap guide-layout"><aside className="guide-toc" aria-label="On this page"><span>On this page</span><a href="#quick-answer">Visual overview</a><a href="#field-notes">Field notes</a><a href="#comparison">Decision table</a><a href="#checklist">Working checklist</a><a href="#mistakes">Common mistakes</a><a href="#questions">Questions</a><a href="#related">Related guides</a><Link className="toc-quote" href={`/${config.key}?quote=1#quote-form`}>Get delivered price</Link></aside><article className="guide-article">
    <section id="quick-answer" className="guide-overview-section"><span className="article-kicker">See the decision</span><KnowledgeVisual config={config} guide={guide}/><div className="guide-decision-flow" aria-label={`${steps.join(", ")} decision flow`}>{steps.map((step,index)=><div key={step}><span>0{index+1}</span><b>{step}</b>{index<steps.length-1&&<i aria-hidden="true">→</i>}</div>)}</div></section>
    <section id="field-notes"><span className="article-kicker">What matters in practice</span><h2>Recommendations that survive the real workflow.</h2><div className="field-note-list">{guide.fieldNotes.map((note,index)=><div key={note}><b>{String(index+1).padStart(2,"0")}</b><p>{note}</p></div>)}</div></section>
    <section id="comparison"><span className="article-kicker">Decision table</span><h2>Verify the variables before using a general rule.</h2><div className="guide-table-wrap"><table><thead><tr>{guide.table.headers.map((header)=><th key={header}>{header}</th>)}</tr></thead><tbody>{guide.table.rows.map((row)=><tr key={row.join("-")}>{row.map((cell,index)=><td key={`${cell}-${index}`}>{cell}</td>)}</tr>)}</tbody></table></div></section>
    <section id="checklist" className="guide-checklist-section"><div className="guide-checklist-head"><div><span className="article-kicker">Take it to the site</span><h2>Working checklist.</h2></div><a className="download-pill" href={download.href} download>Download PDF</a></div><p>Assign an owner, record exceptions and close the loop before purchase or the next operating phase.</p><ol>{guide.checklist.map((item)=><li key={item}><span aria-hidden="true"></span>{item}</li>)}</ol><a className="guide-download-link" href={download.href} download>{download.label}<span>PDF ↓</span></a></section>
    <section id="mistakes"><span className="article-kicker">Avoidable failures</span><h2>Common mistakes that create cost or risk later.</h2><div className="mistake-grid">{guide.mistakes.map((mistake)=><div key={mistake}><span>!</span><p>{mistake}</p></div>)}</div></section>
    <aside className="guide-commercial-cta"><div><span>Need the container next?</span><h2>Get size, condition and delivery in one written price.</h2><p>Send the ZIP and intended use. A specialist will match nearby inventory and confirm access assumptions.</p></div><Link className="button primary" href={`/${config.key}?quote=1#quote-form`}>Get my delivered price</Link></aside>
    <section id="questions"><span className="article-kicker">Questions buyers ask</span><h2>Short answers before you act.</h2><div className="guide-faq">{guide.faq.map((item,index)=><details open={index===0} key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div><Link className="question-library-link" href={`/${config.key}/questions`}><span>100 {config.shortName.toLowerCase()} questions</span><b>Search the complete question library</b><i>→</i></Link></section>
    <section className="guide-sources"><span className="article-kicker">Primary references</span><h2>Rules and specifications used as planning boundaries.</h2><ul>{guide.sources.map((source)=><li key={source.href}><a href={source.href} target="_blank" rel="noreferrer">{source.label} ↗</a></li>)}</ul><p>Confirm the current rule with the authority having jurisdiction, applicable label or owner manual, and the exact specification for the unit being purchased.</p></section>
    <section id="related" className="related-guides"><span className="article-kicker">Keep planning</span><h2>Related {config.shortName.toLowerCase()} container guides.</h2><div>{related.map((item)=><Link key={item.slug} href={`/${config.key}/guides/${item.slug}`}><span>{categoryName(config,item.category)}</span><b>{item.navTitle}</b><i>→</i></Link>)}</div></section>
  </article></div><KnowledgeFooter config={config}/><KnowledgeMobileBar config={config}/></main>;}
