import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { knowledgeConfig, knowledgeKeys } from "../../knowledge/data";
import { KnowledgeFooter, KnowledgeHeader, KnowledgeMobileBar } from "../../knowledge/KnowledgeSiteShell";
import { KnowledgeResourceExplorer } from "../../knowledge/KnowledgeResourceExplorer";

export function generateStaticParams() { return knowledgeKeys.map((vertical) => ({ vertical })); }

export async function generateMetadata({ params }: { params: Promise<{ vertical: string }> }): Promise<Metadata> {
  const { vertical } = await params; const config = knowledgeConfig(vertical); if (!config) return {};
  return { title: `${config.name} Container Resource Center`, description: `32 practical guides, 100 direct answers, a size education center and downloadable reports for ${config.context}.`, alternates: { canonical: `https://unitedcontainerdepot.com/${config.key}/resources` } };
}

export default async function KnowledgeResourcesPage({ params }: { params: Promise<{ vertical: string }> }) {
  const { vertical } = await params; const config = knowledgeConfig(vertical); if (!config) notFound();
  const paths = [config.guides[0], config.guides[4], config.guides[8]];
  return <main className="resource-page knowledge-resource-page"><KnowledgeHeader config={config}/><div className="guide-topbar"><div className="wrap"><Link href={`/${config.key}`}>{config.name} containers</Link><span>/</span><b>Resource center</b></div></div>
    <header className="resource-hero"><div className="wrap resource-hero-grid"><div><span className="eyebrow">{config.name} Resource Center</span><h1>{config.hubTitle}</h1><p>{config.hubLead} Direct answers come first, with verification gates where the exact unit, contents, carrier or local authority controls.</p><div className="resource-hero-actions"><a className="button primary" href="#all-guides">Find a field guide</a><Link className="button outline-light" href={`/${config.key}?quote=1#quote-form`}>Get delivered price</Link></div></div><figure><Image src={config.heroImage} alt={config.heroAlt} fill priority sizes="(max-width: 800px) 100vw, 46vw"/><figcaption><strong>32</strong><span>practical field guides</span><strong>100</strong><span>direct answers</span></figcaption></figure></div></header>
    <section className="resource-paths section"><div className="wrap"><div className="section-heading split-heading"><div><span className="eyebrow dark">Start with the next decision</span><h2>Four fast ways into the library.</h2></div><p>The resource center supports the purchase. If size and ZIP are already known, go directly to the quote.</p></div><div className="resource-path-grid">{paths.map((guide, index) => <Link href={`/${config.key}/guides/${guide.slug}`} key={guide.slug}><span>0{index + 1}</span><h3>{guide.navTitle}</h3><p>{guide.description}</p><b>Open field guide →</b></Link>)}<Link href={`/${config.key}/questions`}><span>100</span><h3>Ask a direct question</h3><p>Search the complete answer library and follow the deeper guide.</p><b>Search questions →</b></Link></div></div></section>
    <section className="knowledge-data-spotlight"><div className="wrap knowledge-data-spotlight-grid"><div className="knowledge-mini-chart" aria-label="20 foot and 40 foot nominal floor area comparison"><span>Source-backed size comparison</span><div><b>20FT</b><i style={{width:"50%"}}>160 SQ FT</i></div><div><b>40FT</b><i style={{width:"100%"}}>320 SQ FT</i></div><small>Nominal floor area only. Interior and door dimensions vary by exact unit.</small></div><div><span className="eyebrow">Size education</span><h2>Choose a size and see what it is built to handle.</h2><p>Compare proportional 20FT, 40FT and High Cube visuals, capacity and vertical-specific uses. Carry the chosen size directly into the quote form.</p><div><Link className="button primary" href={`/${config.key}/planner`}>Compare container sizes</Link><Link className="button outline-light" href={`/${config.key}/resources/planning-brief`}>Open planning brief</Link></div></div></div></section>
    <section className="section resource-library" id="all-guides"><div className="wrap"><div className="section-heading split-heading"><div><span className="eyebrow dark">Complete guide library</span><h2>Find the exact storage decision.</h2></div><p>Filter by topic or search in the language you use. Every guide links to related decisions, a printable report and a delivered-price request.</p></div><KnowledgeResourceExplorer vertical={config.key} guides={config.guides} categories={config.categories}/></div></section>
    <section className="section resource-downloads" id="downloads"><div className="wrap"><div className="section-heading split-heading"><div><span className="eyebrow dark">Downloadable field library</span><h2>Print it. Mark it up. Use it before delivery.</h2></div><p>Four substantial resources with explicit limits, decision gates and space for site-specific notes.</p></div><div className="report-grid">{config.downloads.map((item, index) => <a href={item.href} download key={item.href}><div><span>{String(index + 1).padStart(2,"0")}</span><em>PDF</em></div><h3>{item.label}</h3><p>{item.description}</p><b>Download PDF ↓</b></a>)}</div></div></section>
    <section className="resource-conversion-cta"><div className="wrap"><div><span className="eyebrow">Ready to price the container?</span><h2>Turn the plan into one delivered number.</h2><p>Send the delivery ZIP, likely size and use. A specialist will match nearby inventory and review access.</p></div><div><Link className="button primary" href={`/${config.key}?quote=1#quote-form`}>Get my delivered price</Link><a href="tel:18555250902">Call (855) 525-0902</a></div></div></section><KnowledgeFooter config={config}/><KnowledgeMobileBar config={config}/>
  </main>;
}
