import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { knowledgeConfig, knowledgeKeys } from "../../knowledge/data";
import { KnowledgePlanner } from "../../knowledge/KnowledgePlanner";
import { KnowledgeFooter, KnowledgeHeader, KnowledgeMobileBar } from "../../knowledge/KnowledgeSiteShell";

export function generateStaticParams() { return knowledgeKeys.map((vertical) => ({ vertical })); }
export async function generateMetadata({params}:{params:Promise<{vertical:string}>}):Promise<Metadata>{const{vertical}=await params;const config=knowledgeConfig(vertical);if(!config)return{};return{title:`${config.name} Container Planning Tool`,description:`Build a safe starting shortlist for ${config.context} before requesting local inventory.`};}
export default async function PlannerPage({params}:{params:Promise<{vertical:string}>}){const{vertical}=await params;const config=knowledgeConfig(vertical);if(!config)notFound();return <main className="resource-page"><KnowledgeHeader config={config}/><div className="guide-topbar"><div className="wrap"><Link href={`/${config.key}`}>{config.name} containers</Link><span>/</span><Link href={`/${config.key}/resources`}>Resource center</Link><span>/</span><b>Planning tool</b></div></div><header className="planner-hero"><div className="wrap"><span className="eyebrow">Screen the first comparison</span><h1>Build a starting container shortlist without pretending the exact unit is known.</h1><p>Three operational questions produce a quote starting point. The tool does not approve fit, site, contents or delivery.</p></div></header><section className="section planner-section"><div className="wrap"><KnowledgePlanner config={config}/><div className="planner-limits"><span className="eyebrow dark">What this tool does not decide</span><h2>The exact unit and site still control.</h2><div>{config.safetyGates.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></div></section><section className="resource-conversion-cta"><div className="wrap"><div><span className="eyebrow">Ready for local inventory?</span><h2>Send the shortlist and delivery ZIP.</h2><p>A specialist will confirm the exact unit, condition, delivered price and access assumptions.</p></div><div><Link className="button primary" href={`/${config.key}?quote=1#quote-form`}>Get my delivered price</Link><a href="tel:18555250902">Call (855) 525-0902</a></div></div></section><KnowledgeFooter config={config}/><KnowledgeMobileBar config={config}/></main>;}
