export type GuideTable = {
  headers: string[];
  rows: string[][];
};

export type KnowledgeGuide = {
  slug: string;
  title: string;
  navTitle: string;
  category: string;
  description: string;
  quickAnswer: string;
  fieldNotes: string[];
  checklist: string[];
  mistakes: string[];
  table?: GuideTable;
  faq: { q: string; a: string }[];
  sources?: { label: string; href: string }[];
};

export const guideCategories = [
  { key: "security", name: "Security", description: "Locks, lighting, cameras, tool control and the nightly closeout routine.", number: "01" },
  { key: "buying", name: "Buying Guides", description: "Choose the right size, condition and ownership model for the project.", number: "02" },
  { key: "planning", name: "Site Planning", description: "Prepare access, bearing points, drainage and final placement before delivery day.", number: "03" },
  { key: "specifications", name: "Dimensions & Specs", description: "Interior space, door openings, payload, floor loading and high cube tradeoffs.", number: "04" },
  { key: "operations", name: "Jobsite Operations", description: "Shelving, power, ventilation, moisture control and risk-based inspections.", number: "05" },
  { key: "regulations", name: "Safety & Regulations", description: "Practical OSHA, fire, permit and insurance considerations for site teams.", number: "06" },
  { key: "use-cases", name: "Trade Use Cases", description: "Storage layouts for builders, specialty trades and infrastructure crews.", number: "07" },
  { key: "costs", name: "Cost & Ownership", description: "Delivered-price planning, modification budgets and total cost of ownership.", number: "08" },
  { key: "faq", name: "Construction FAQ", description: "Direct answers to the questions contractors ask before ordering and delivery.", number: "09" },
  { key: "field-scenarios", name: "Field Scenarios", description: "Worked storage plans for small builders, commercial sites, infrastructure and temporary work.", number: "10" },
] as const;

export const guides: KnowledgeGuide[] = [
  {
    slug: "construction-site-theft-prevention",
    title: "Construction Site Theft Prevention: A Container Security Plan That Crews Will Actually Follow",
    navTitle: "Theft prevention plan",
    category: "security",
    description: "Build layered jobsite security around placement, locks, lighting, cameras, inventory control and a repeatable nightly closeout.",
    quickAnswer: "A container is only one layer. The strongest setup combines visible placement, a protected lock, controlled keys, lighting, camera coverage and a closeout routine with a named owner.",
    fieldNotes: [
      "Place the cargo doors where they can be seen from the trailer, occupied building or camera, but not directly from the public road.",
      "Use the container for high-value portable tools. Keep bulk low-value material outside only when weather and theft exposure are acceptable.",
      "Create one lock-up time. A container that is open all afternoon with no accountable closer is not a secure system.",
      "Record serial numbers before equipment reaches the site. A photo of the tool and serial plate is faster than rebuilding an inventory after a loss.",
    ],
    checklist: ["Assign one closeout owner and one backup", "Check both cargo-door cams are fully seated", "Lock the lockbox and photograph the closed doors", "Confirm camera view and lighting", "Remove ladders or objects that create roof access", "Escalate missing tools before the crew leaves"],
    mistakes: ["Hiding the container so well that no one can observe it", "Sharing one uncontrolled key across every subcontractor", "Leaving gang boxes outside while the container sits half empty", "Installing a camera without checking its night view"],
    table: { headers: ["Layer", "What it stops", "Field standard"], rows: [["Placement", "Unobserved attack", "Doors inside a controlled, visible zone"], ["Lockbox", "Bolt-cutter access", "Shrouded lock sized to the box"], ["Lighting", "Dark working conditions", "Even coverage without camera glare"], ["Inventory", "Unnoticed loss", "Serial record plus issue/return owner"], ["Closeout", "Doors left unsecured", "Named person signs off nightly"]] },
    faq: [{ q: "Should the doors face the street?", a: "Usually no. Keep delivery access workable, but orient the doors toward controlled site activity or verified camera coverage rather than public view." }, { q: "Does a heavier lock solve most theft risk?", a: "It helps only if the lock is protected and the door hardware, key control and surrounding site are also managed." }],
  },
  {
    slug: "shipping-container-locks-lockboxes",
    title: "Shipping Container Locks and Lockboxes for Construction Sites",
    navTitle: "Locks and lockboxes",
    category: "security",
    description: "Understand the difference between padlocks, hidden-shackle locks, puck locks and welded lockboxes before securing jobsite tools.",
    quickAnswer: "Use a quality hidden-shackle or container-specific lock inside a correctly sized steel lockbox. The lockbox should limit tool access without making routine locking difficult for the superintendent.",
    fieldNotes: ["Measure the lockbox opening before buying the lock. A strong lock that does not fit cleanly will be left unused.", "Choose corrosion-resistant hardware when the container will sit through a wet season.", "Keep the spare key off site with a designated manager, not under the trailer steps.", "Inspect hinges, rods, handles and lockbox welds. Security is limited by the weakest exposed point."],
    checklist: ["Measure lockbox clearance", "Select a shielded, weather-resistant lock", "Issue numbered keys or controlled codes", "Lubricate only with a product suitable for the lock", "Check closing cams and door gaskets", "Document who can authorize a duplicate key"],
    mistakes: ["Buying by shackle thickness alone", "Using a long exposed shackle", "Leaving the lock on the ground when doors are open", "Grinding or welding on the box without checking the container condition"],
    table: { headers: ["Lock type", "Jobsite fit", "Main limitation"], rows: [["Standard padlock", "Low-risk temporary use", "Exposed shackle"], ["Hidden-shackle", "Good general choice", "Must fit the lockbox"], ["Puck lock", "Useful with matching hardware", "Hardware compatibility"], ["Crossbar lock", "Visible secondary deterrent", "More handling and storage"]] },
    faq: [{ q: "Can one lock secure both doors?", a: "Yes. Standard cargo doors interlock through the closing gear, so the protected lock usually secures the active door after both doors are fully closed." }, { q: "Should we use a combination lock?", a: "Only when the code can be controlled and changed. Shared codes often spread farther than intended." }],
  },
  {
    slug: "jobsite-cameras-lighting-gps",
    title: "Camera, Lighting and GPS Placement Around a Jobsite Container",
    navTitle: "Cameras, lighting and GPS",
    category: "security",
    description: "Position security technology so it captures useful evidence and supports the container instead of creating glare, blind spots or false confidence.",
    quickAnswer: "Cover the approach and the cargo doors from separate angles, light faces rather than the camera lens, and place trackers inside valuable equipment rather than relying on one obvious device on the container.",
    fieldNotes: ["A camera directly above the doors often records helmets and hats rather than faces. Add an approach angle at usable height.", "Test the scene after dark with the actual work lights on. Reflective vests and white doors can overexpose the image.", "Keep the recorder or communications equipment outside the container being protected.", "Use tamper and offline alerts so a disconnected camera produces an action, not just missing footage."],
    checklist: ["Capture license plates at the vehicle approach", "Capture faces at the pedestrian approach", "Eliminate backlight and IR reflection", "Confirm network or local recording health", "Set an escalation contact", "Review footage after layout changes"],
    mistakes: ["Pointing every camera at the same door angle", "Mounting lights behind the subject", "Putting all equipment on one easy-to-cut power source", "Using GPS without an owner who receives alerts"],
    faq: [{ q: "Is one camera enough?", a: "One camera can confirm activity, but two angles are usually needed to capture both the approach and the actual door interaction." }, { q: "Where should a tracker go?", a: "Use trackers on selected high-value mobile assets and follow the device manufacturer's installation and legal guidance." }],
  },
  {
    slug: "overnight-tool-security-checklist",
    title: "Overnight Tool Security Checklist for Superintendents",
    navTitle: "Overnight security checklist",
    category: "security",
    description: "A practical ten-minute end-of-shift routine for locking tools, recording exceptions and handing off responsibility.",
    quickAnswer: "The checklist should be short enough to complete every day: recover high-value tools, reconcile exceptions, close both cargo doors, lock the box, verify the camera view and record the closer.",
    fieldNotes: ["Do not make the closer count every drill bit. Focus the daily check on portable, high-value and frequently missing equipment.", "Use a red-tag area inside the door for damaged or unverified tools so they are not silently returned to service.", "Photograph the locked doors with the date and project location automatically recorded by the approved system.", "Review repeat exceptions weekly. The same missing charger or shared saw usually points to a process problem."],
    checklist: ["Call last tool return", "Sweep active floors and gang boxes", "Reconcile signed-out high-value tools", "Store batteries away from heat and ignition sources", "Clear the interior aisle", "Close passive door, then active door", "Seat all cams", "Lock and verify", "Check lighting and camera", "Record closer and exceptions"],
    mistakes: ["Making the form longer than the actual closeout", "Treating an open container as secure because the site fence is locked", "Charging damaged batteries unattended", "Failing to assign weekend responsibility"],
    faq: [{ q: "Who should own the checklist?", a: "The superintendent or a named designee should own completion. Responsibility should not rotate informally at the end of the shift." }, { q: "Should every subcontractor have access?", a: "No. Use the smallest practical access group and document how after-hours access is approved." }],
  },
  {
    slug: "construction-container-buying-guide",
    title: "The Complete Construction Storage Container Buying Guide",
    navTitle: "Complete buying guide",
    category: "buying",
    description: "A contractor-first framework for choosing size, condition, doors, delivery method and modifications without overbuying.",
    quickAnswer: "Start with the longest project, the largest items and the actual placement area. Choose size before condition, verify delivered price before cosmetic preferences, and confirm truck access before paying for modifications.",
    fieldNotes: ["A 20FT unit is easier to place on constrained urban sites. A 40FT unit usually offers lower cost per square foot when access is available.", "Used wind-and-watertight containers are often the practical jobsite choice. One-trip units make sense when appearance, remaining service life or client-facing placement matters.", "Ask for the delivered total to your ZIP, not the depot price alone.", "Treat shelving, power and personnel doors as an operating plan. Random modifications can reduce flexibility and resale value."],
    checklist: ["List the largest stored items", "Estimate required floor area plus aisle", "Measure placement and delivery approach", "Choose 20FT, 40FT or high cube", "Select condition grade", "Specify required modifications", "Confirm delivered price", "Inspect on arrival before loading"],
    mistakes: ["Buying from a photo without a condition definition", "Ignoring delivery access until the truck arrives", "Filling the entire floor with no retrieval aisle", "Choosing high cube only because it sounds larger"],
    table: { headers: ["Project condition", "Usually start with", "Why"], rows: [["Tight infill site", "20FT standard", "Placement and turning flexibility"], ["Large commercial site", "40FT standard", "Capacity and value per square foot"], ["Bulky palletized stock", "40FT high cube", "More vertical clearance"], ["Client-facing long-term use", "One-trip or refurbished", "Appearance and remaining life"]] },
    faq: [{ q: "What should be in a written quote?", a: "Size, type, condition, quantity, delivery ZIP, delivered total, expected lead time, placement assumptions and any modifications." }, { q: "Can I inspect the exact unit?", a: "Availability varies. Ask whether the quote covers a grade or a specific container and what inspection options are available." }],
  },
  {
    slug: "rent-vs-buy-construction-container",
    title: "Renting vs Buying a Construction Storage Container",
    navTitle: "Renting vs buying",
    category: "buying",
    description: "Compare project duration, repeat use, mobilization, modification freedom and exit value before committing to rent or buy.",
    quickAnswer: "Renting fits short, uncertain assignments with a clear pickup date. Buying becomes stronger when the container will serve multiple phases or future projects, when modifications matter, or when monthly rental and repeated transport costs accumulate.",
    fieldNotes: ["Count every expected move, delivery and pickup, not just the monthly rate.", "If the next project is already awarded, ownership can bridge the gap between jobs.", "Rental agreements may restrict drilling, welding, painting or electrical work.", "Ownership adds responsibility for transport, storage between projects and eventual resale."],
    checklist: ["Estimate months on the first project", "Add likely future projects", "List required modifications", "Price delivery and pickup for both options", "Assign between-project storage", "Estimate conservative resale value", "Compare total cash cost and flexibility"],
    mistakes: ["Comparing purchase price to one month of rent", "Leaving pickup and damage fees out", "Assuming a purchased container can move loaded without written carrier approval", "Treating resale value as guaranteed"],
    table: { headers: ["Factor", "Rent tends to win", "Buy tends to win"], rows: [["Duration", "Short and defined", "Long or repeated"], ["Modifications", "None or minor", "Shelving, power, access"], ["Future use", "Unknown", "Likely"], ["Exit", "Vendor pickup", "Storage, transfer or resale"]] },
    faq: [{ q: "What is the break-even month?", a: "It depends on local rates, transport, condition and resale. Use total ownership cost, not a simple purchase-price divided by monthly-rent calculation." }, { q: "Can a purchased unit move between sites?", a: "Yes, with a qualified carrier and suitable access. Never assume it can move loaded. Obtain written carrier approval for the actual gross weight, distribution and securement; many carriers require an empty unit." }],
  },
  {
    slug: "one-trip-vs-used-container",
    title: "One-Trip vs Used Containers for Construction Sites",
    navTitle: "One-trip vs used",
    category: "buying",
    description: "Choose condition based on weather resistance, appearance, service life and project reality rather than paint alone.",
    quickAnswer: "A sound used wind-and-watertight container is usually the value choice for active jobsites. Choose one-trip when appearance, client visibility, sensitive contents or longer remaining life justifies the premium.",
    fieldNotes: ["Surface rust and dents do not automatically mean leakage. Inspect roof, corner posts, door operation, floor and light penetration.", "Fresh paint can improve appearance but should not replace a condition inspection.", "Odor and prior cargo history matter when storing finishes, fabric, records or occupied-workspace materials.", "Door effort matters every day. A cheaper unit with misaligned doors becomes an operating problem."],
    checklist: ["Verify condition grade in writing", "Check roof and wall patches", "Open and close both doors", "Inspect gasket continuity", "Look for daylight from inside", "Check floor damage and odor", "Confirm lockbox and vents"],
    mistakes: ["Equating cosmetic wear with structural failure", "Equating new paint with a one-trip unit", "Ignoring door alignment", "Loading before documenting delivery condition"],
    table: { headers: ["Condition", "Best fit", "Watch for"], rows: [["One-trip", "Visible or long-term placement", "Higher acquisition cost"], ["Cargo-worthy used", "Transport-capable requirements", "Certification timing"], ["Wind and watertight", "Stationary jobsite storage", "Cosmetic variation"], ["As-is", "Repair-capable buyer", "Unknown repair cost"]] },
    faq: [{ q: "Does used mean it leaks?", a: "No. A properly graded wind-and-watertight unit should protect stationary contents from normal weather, but inspect the specific condition and warranty terms." }, { q: "Is one-trip completely new?", a: "It normally means the container completed one cargo trip from its manufacturing region. Minor handling marks can still be present." }],
  },
  {
    slug: "20ft-vs-40ft-construction",
    title: "20FT vs 40FT Containers for Construction Sites",
    navTitle: "20FT vs 40FT",
    category: "buying",
    description: "Match capacity to access, crew count, project phase and retrieval needs with a practical size decision framework.",
    quickAnswer: "Choose 20FT when placement and frequent access matter more than maximum capacity. Choose 40FT when the site can accept the truck and the project needs separate zones for tools, material and an aisle.",
    fieldNotes: ["Two 20FT containers can outperform one 40FT when trades work at opposite ends of a large site.", "A 40FT container provides twice the nominal floor area but needs a longer straight delivery zone.", "Overfilled 20FT units lose time because the item needed first is often behind the item delivered last.", "High cube adds one foot of exterior height. It does not add width."],
    checklist: ["Measure placement length", "Confirm truck approach", "Count simultaneous crews", "List long or bulky items", "Reserve retrieval aisle", "Plan phase changes", "Compare one 40FT with two 20FT units"],
    mistakes: ["Sizing only by cubic feet", "Ignoring where doors will open", "Using the container as a deep pile", "Choosing one large unit when the site has two work fronts"],
    table: { headers: ["Decision point", "20FT", "40FT"], rows: [["Nominal floor area", "About 160 sq ft", "About 320 sq ft"], ["Tight sites", "Better fit", "More difficult"], ["Trade zoning", "Limited", "Strong"], ["Relocation", "Simpler", "Requires more clearance"]] },
    faq: [{ q: "Does a 40FT cost twice as much?", a: "Usually not. Pricing and delivery vary, but larger containers often provide a lower acquisition cost per square foot." }, { q: "Can a 20FT hold a full crew's tools?", a: "Often yes for a small crew with disciplined shelving. Large equipment or multiple trades may justify a 40FT unit." }],
  },
  {
    slug: "container-site-preparation",
    title: "How to Prepare a Construction Site for Container Delivery",
    navTitle: "Site preparation",
    category: "planning",
    description: "Prepare firm bearing points, drainage, access and a placement plan before the delivery truck reaches the gate.",
    quickAnswer: "Choose a firm, level, well-drained bearing system sized for the actual unit, loaded weight, soil and duration. Clear the carrier-approved approach and overhead envelope, mark the cargo-door end and keep everyone outside the unload exclusion zone.",
    fieldNotes: ["Ordinary unmodified ISO containers commonly transfer major loads through the corner structures, but modifications, unusual loading and permanent or occupied use can change the support design.", "Keep the container level and grade the surrounding base away from the doors. Do not deliberately slope or twist the box to create drainage.", "Walk the route at truck height, not pickup-truck height. The carrier and utility owner must review power lines and other overhead hazards.", "Paint or stake the final footprint and mark DOORS so the driver does not have to interpret a phone photo."],
    checklist: ["Confirm permits and owner approval", "Measure footprint and door swing", "Verify firm all-weather access", "Review overhead and underground utilities", "Approve bearing system", "Establish drainage", "Mark door end and unload zone", "Assign delivery contact"],
    mistakes: ["Using loose fill placed the morning of delivery", "Supporting only two corners", "Forgetting that cargo doors need working space", "Letting delivery block fire access or the next concrete pour"],
    table: { headers: ["Surface", "Advantage", "Control needed"], rows: [["Compacted gravel", "Drainage and adjustability", "Compaction and erosion"], ["Concrete", "Stable long-term base", "Slope and cost"], ["Asphalt", "Clean access", "Point-load settlement in heat"], ["Timber/block supports", "Quick leveling", "Rated material and inspection"]] },
    faq: [{ q: "Must the entire floor be supported?", a: "An ordinary unmodified ISO container commonly bears at its corner structures. Soil, loading, duration, modifications and local rules can change the foundation design, so verify the actual unit and site." }, { q: "How level is level enough?", a: "Keep the frame level in both directions, stable and free of twist. Both doors should operate without binding. Grade the surrounding base for drainage instead of sloping the box." }],
    sources: [{ label: "OSHA 1926.416 electrical hazards", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.416" }, { label: "ICC container foundation guidance", href: "https://codes.iccsafe.org/content/ICCG52019/current-code-requirements" }],
  },
  {
    slug: "container-delivery-clearance",
    title: "Construction Container Delivery Clearance and Truck Access",
    navTitle: "Delivery clearance",
    category: "planning",
    description: "Plan straight-line room, width, height, turning area and ground conditions for tilt-bed container delivery.",
    quickAnswer: "The delivery truck needs more than the container footprint. Confirm a straight approach, turning room, overhead clearance and a firm path with the carrier using current site photos and measurements.",
    fieldNotes: ["Required length varies by truck, trailer, container size and whether the container comes off doors-first or doors-last.", "Do not publish one universal clearance number as a promise. Give the carrier measured site conditions and get approval.", "A gate may be wide enough while the turn immediately inside is not.", "Weather can turn approved soil into an inaccessible route. Establish a rain-day decision owner."],
    checklist: ["Measure gate width", "Measure narrowest turn", "Measure straight approach", "Check overhead utilities", "Check side obstructions", "Confirm slope and cross-slope", "Send current photos", "Confirm unload orientation", "Keep route clear on delivery day"],
    mistakes: ["Measuring only the final footprint", "Assuming a crane solves poor access", "Ignoring parked vehicles and material deliveries", "Approving access from an old site plan"],
    faq: [{ q: "Can the driver turn the container during unloading?", a: "Placement options depend on equipment and space. Confirm door orientation before dispatch rather than relying on an on-site change." }, { q: "Can a crane place it over a fence?", a: "Sometimes, but crane planning requires a qualified lift plan, verified weights, rigging, ground conditions and clearance. It is a different delivery scope." }],
  },
  {
    slug: "container-foundations-gravel-concrete",
    title: "Container Foundations: Gravel, Concrete and Corner Supports",
    navTitle: "Foundation options",
    category: "planning",
    description: "Compare practical base options for temporary construction use and longer-term container placement.",
    quickAnswer: "Compacted, well-drained aggregate with a properly designed bearing system can work for temporary, unoccupied storage. Permanent, occupied, structurally modified or unusually loaded units require local review and may require a site-specific engineered foundation.",
    fieldNotes: ["The base must manage both bearing and drainage. A strong pad that traps water at the door is not a complete solution.", "Keep steel off persistent wet soil to reduce corrosion at the lower rails and corners.", "Recheck level after the first heavy loading cycle and after freeze-thaw or major rain.", "Modified containers with large side openings may need engineered support beyond standard corner bearing."],
    checklist: ["Evaluate soil and drainage", "Define temporary or long-term duration", "Choose base material", "Compact in lifts when required", "Set stable corner supports", "Verify diagonal level", "Test doors", "Schedule reinspection"],
    mistakes: ["Placing on four loose pavers over soft soil", "Creating a center high point", "Ignoring runoff from adjacent roofs", "Treating a modified unit like an unmodified box"],
    table: { headers: ["Base", "Potential use", "Control needed"], rows: [["Compacted aggregate", "Temporary storage", "Designed bearing and drainage"], ["Concrete strips/pads", "Long duration", "Site-specific foundation review"], ["Rated precast supports", "Rapid setup", "Verified soil bearing and stability"], ["Direct soil", "Avoid unless approved", "Settlement, twist and corrosion control"]] },
    faq: [{ q: "Can railroad ties be used?", a: "Only when a qualified site reviewer confirms their condition, bearing area, stability and compatibility with the support plan. Do not improvise with split, decayed or unstable timber." }, { q: "Does a container need anchors?", a: "Anchoring depends on wind, flood, local code, exposure and use. Ask the authority having jurisdiction and a qualified engineer when required." }],
    sources: [{ label: "ICC container foundation guidance", href: "https://codes.iccsafe.org/content/ICCG52019/current-code-requirements" }, { label: "2024 IBC special construction", href: "https://codes.iccsafe.org/content/IBC2024V1.0/chapter-31-special-construction" }],
  },
  {
    slug: "jobsite-container-layout",
    title: "Jobsite Container Layout Planning",
    navTitle: "Jobsite layout",
    category: "planning",
    description: "Place storage to reduce walking and material handling without blocking emergency access, deliveries or future phases.",
    quickAnswer: "Put the container close enough to the work to save steps, but outside crane swing, delivery conflict, excavation expansion and emergency routes. Plan where it will serve the next phase, not only today's crew.",
    fieldNotes: ["A perfect phase-one location can become phase-two excavation. Review the three-week look-ahead before placement.", "Separate pedestrian access from forklift and delivery paths where practical.", "Create a clean apron at the doors. Mud at the threshold moves inside and creates slip risk.", "If several trades share one unit, mark zones before the first load arrives."],
    checklist: ["Overlay the three-week look-ahead", "Check fire and emergency routes", "Check crane and equipment envelopes", "Protect pedestrian access", "Reserve door apron", "Plan lighting and camera view", "Mark trade zones", "Define relocation trigger"],
    mistakes: ["Placing under future scaffolding", "Blocking sight lines at a gate", "Allowing material stacks to consume the door apron", "Moving the container only after it becomes an obstruction"],
    faq: [{ q: "How close should it be to the active work?", a: "Close enough to reduce handling, but outside changing work zones and traffic conflicts. There is no universal distance." }, { q: "Should several trades share one container?", a: "Yes when access and zones are controlled. Otherwise one trade's material can block another's tools." }],
  },
  {
    slug: "container-dimensions-specifications",
    title: "20FT and 40FT Container Dimensions for Construction Storage",
    navTitle: "Dimensions and measurements",
    category: "specifications",
    description: "Use nominal and actual interior dimensions correctly when checking tools, pallets, doors and site fit.",
    quickAnswer: "Nominal length is not usable interior length. Verify the specific container data plate and measured door opening before planning tight equipment clearance.",
    fieldNotes: ["Standard dry containers are commonly 8FT wide externally. Standard height is commonly 8FT 6IN, while high cube is commonly 9FT 6IN.", "Interior length and height are smaller because of wall, roof and floor construction.", "Door opening height is lower than the interior height. The doorway, not the center of the box, controls tall equipment entry.", "Published values vary slightly by manufacturer and series. Treat the exact unit specification as controlling."],
    checklist: ["Measure the stored item at its widest fixed point", "Include handles, guards and packaging", "Check door opening width and height", "Check turning space outside doors", "Check interior aisle", "Verify exact unit specification"],
    mistakes: ["Using exterior height as door height", "Assuming every 40FT unit has identical tare weight", "Planning zero clearance around equipment", "Ignoring floor transition and loading ramp angle"],
    table: { headers: ["Type", "Nominal exterior length", "Nominal exterior height", "Approx. floor area"], rows: [["20FT standard", "20FT", "8FT 6IN", "160 sq ft"], ["40FT standard", "40FT", "8FT 6IN", "320 sq ft"], ["40FT high cube", "40FT", "9FT 6IN", "320 sq ft"]] },
    faq: [{ q: "Why do online dimensions differ?", a: "Manufacturing series and measurement conventions differ slightly. Use published dimensions for planning, then verify the specific unit before a tight fit." }, { q: "Is high cube wider?", a: "No. The common difference is one additional foot of exterior height." }],
    sources: [{ label: "Hapag-Lloyd container specifications", href: "https://www.hapag-lloyd.com/content/dam/website/downloads/pdf/17038_Update_Container_Specification_engl_sRGB.pdf" }],
  },
  {
    slug: "container-payload-floor-loading",
    title: "Container Payload, Floor Loading and Heavy Construction Equipment",
    navTitle: "Payload and floor loading",
    category: "specifications",
    description: "Separate total payload from concentrated wheel and point loads before storing heavy equipment or dense material.",
    quickAnswer: "A container's maximum payload does not mean every small floor area can carry that load. Verify the exact data plate, floor condition and point loads, then obtain qualified engineering guidance for unusually heavy equipment or support conditions.",
    fieldNotes: ["Payload is gross rating minus tare weight. The exact door plate controls for the unit.", "A compact machine can create higher local floor stress than a larger evenly distributed load.", "Use rated dunnage or load-spreading plates only when the plan will not damage the floor or create instability.", "Never exceed delivery or carrier weight limits because the container itself can carry the load."],
    checklist: ["Record unit tare and maximum gross", "Calculate actual cargo weight", "Identify wheel and outrigger loads", "Plan load distribution", "Check floor condition", "Confirm ramp and dockboard rating", "Confirm future transport limits"],
    mistakes: ["Reading payload as point-load capacity", "Loading damaged flooring", "Using an unrated ramp", "Planning stationary storage without considering eventual unloading"],
    faq: [{ q: "Can a skid steer be stored inside?", a: "Possibly, if dimensions, floor condition, point loads, ramp capacity and ventilation are all addressed. Verify the exact machine and container." }, { q: "Can the container be transported loaded?", a: "Only with a qualified carrier and a compliant load plan. Site storage capacity and road transport limits are separate questions." }],
    sources: [{ label: "Maersk cargo weight guidance", href: "https://www.maersk.com/support/faqs/containers/cargo-weight-limit" }, { label: "FMCSA cargo securement rules", href: "https://www.fmcsa.dot.gov/regulations/cargo-securement/cargo-securement-rules" }],
  },
  {
    slug: "high-cube-construction-guide",
    title: "When a High Cube Container Helps on a Construction Site",
    navTitle: "High cube guide",
    category: "specifications",
    description: "Decide whether one extra foot of height creates usable value for bulky equipment, pallet stacking or interior systems.",
    quickAnswer: "Choose high cube when the exact door opening and added interior height solve a specific storage problem. It can help with tall equipment or professionally designed vertical storage. Added height alone does not make a unit suitable for occupancy.",
    fieldNotes: ["High cube does not add floor area. Poor shelving will waste the added volume.", "The door opening remains the entry constraint. Confirm equipment height at the doorway.", "The extra exterior height can affect trees, canopies and visual restrictions.", "For hand-loaded tools, standard height may be easier to use because top shelves remain reachable."],
    checklist: ["Identify items over standard door clearance", "Plan vertical storage", "Check safe retrieval height", "Check exterior overhead clearance", "Compare delivered price", "Confirm high cube availability"],
    mistakes: ["Buying height with no storage plan", "Stacking unstable material higher", "Ignoring access equipment for top shelves", "Assuming high cube increases payload"],
    faq: [{ q: "How much taller is high cube?", a: "The common exterior height is 9FT 6IN, one foot taller than a standard 8FT 6IN dry container. Interior and door dimensions vary by manufacturer, so verify the actual unit." }, { q: "Is high cube always 40FT?", a: "High cube configurations exist in multiple lengths, but local sale inventory commonly emphasizes 40FT high cube units." }],
    sources: [{ label: "Hapag-Lloyd 40FT High Cube specifications", href: "https://www.hapag-lloyd.com/en/services-information/cargo-fleet/container/40-standard-high-cube.html" }],
  },
  {
    slug: "container-tool-organization-shelving",
    title: "Construction Container Shelving and Tool Organization",
    navTitle: "Shelving and organization",
    category: "operations",
    description: "Turn a steel box into a retrieval system with zones, aisles, shelf limits and return locations that crews can maintain.",
    quickAnswer: "Keep one clear center aisle, place heavy items low, assign zones by work type and put the highest-frequency tools nearest the doors. Every item needs a visible return location.",
    fieldNotes: ["The first eight feet inside the doors becomes congested unless it is intentionally designed.", "Use shelf labels that match how crews speak, such as layout, cordless, electrical and safety, not accounting categories.", "Store consumables in forward-facing bins so the superintendent can see reorder level without opening boxes.", "Do not attach shelving through structural members without an approved modification plan."],
    checklist: ["Map high-frequency items", "Reserve center aisle", "Place heavy items below waist height", "Create trade or task zones", "Label shelves and floor bays", "Set maximum shelf loads", "Create battery and damaged-tool areas", "Audit weekly"],
    mistakes: ["Installing deep shelves on both sides of a 20FT unit", "Storing long stock across the aisle", "Mixing returned and damaged tools", "Using the floor as overflow until doors will not close"],
    table: { headers: ["Zone", "Best location", "Typical contents"], rows: [["Fast issue", "Inside active door", "PPE, chargers, daily tools"], ["Heavy", "Low and over bearing path", "Compact equipment, dense fittings"], ["Long stock", "Dedicated rack side", "Conduit, trim, levels"], ["Controlled", "Locked inner cabinet", "Lasers, test gear, high-value tools"]] },
    faq: [{ q: "How wide should the aisle be?", a: "Wide enough for the actual person, cart or handling equipment and kept unobstructed. OSHA requires aisles and passageways to remain clear for safe movement." }, { q: "Can shelving be welded in?", a: "Yes only with a competent modification plan that considers structure, coatings, fire risk and future use." }],
    sources: [{ label: "OSHA 1926.250 storage requirements", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.250" }],
  },
  {
    slug: "container-electrical-lighting",
    title: "Electrical Power and Lighting Inside a Construction Container",
    navTitle: "Electrical and lighting",
    category: "operations",
    description: "Plan safe power, lighting, grounding, cable protection and temporary-service removal with a qualified electrician.",
    quickAnswer: "Use a qualified electrician and listed equipment. Protect conductors from abrasion, close unused openings, provide appropriate grounding and overcurrent protection, and design lighting so crews can enter without crossing a dark floor.",
    fieldNotes: ["A steel container is an enclosure, not an electrical raceway by default.", "Protect every cable penetration from sharp corrugated steel edges and weather entry.", "Put the light switch where it can be reached from outside or immediately inside the door.", "Battery charging creates heat and fire considerations. Follow tool and battery manufacturer instructions."],
    checklist: ["Define temporary or permanent use", "Use qualified electrical design", "Select listed weather-suitable components", "Protect penetrations", "Provide grounding and GFCI protection as applicable", "Maintain clear panel access", "Label circuits", "Remove temporary wiring when its purpose ends"],
    mistakes: ["Running household extension cords through door gaps", "Leaving uncovered boxes", "Mounting chargers against combustible storage", "Using lighting with no emergency exit visibility"],
    faq: [{ q: "Can I power it with an extension cord?", a: "Temporary wiring on construction sites has specific requirements. Have a qualified person evaluate the installation rather than treating a container like a household appliance." }, { q: "Does the steel shell need grounding?", a: "Grounding and bonding depend on the electrical system and local requirements. A qualified electrician should determine the correct method." }],
    sources: [{ label: "OSHA 1926.405 wiring methods", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.405" }, { label: "OSHA 1926.416 electrical hazards", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.416" }],
  },
  {
    slug: "container-ventilation-moisture-control",
    title: "Ventilation and Moisture Control for Jobsite Containers",
    navTitle: "Ventilation and moisture",
    category: "operations",
    description: "Reduce condensation by controlling what enters the container, improving airflow and monitoring real conditions.",
    quickAnswer: "Keep wet materials out, maintain intact vents, create airflow around stored goods and monitor humidity. Add mechanical ventilation, insulation or dehumidification only after identifying the actual moisture source and power plan.",
    fieldNotes: ["Condensation can occur even when the roof does not leak. Warm humid air meeting cool steel creates moisture.", "Wet lumber, rain-soaked cords and uncured materials can load the interior with moisture.", "Pushing boxes against walls blocks airflow and hides condensation.", "Desiccants help small enclosed volumes but are not a substitute for ventilation in a frequently opened construction container."],
    checklist: ["Inspect roof and gaskets", "Keep wet material out", "Raise sensitive goods off the floor", "Leave wall airflow gaps", "Keep vents clear", "Use a humidity monitor", "Match ventilation to climate and contents", "Document recurring condensation"],
    mistakes: ["Calling every moisture mark a roof leak", "Blocking vents with shelving", "Sealing the container tighter without a humidity plan", "Running an unmonitored residential dehumidifier on temporary power"],
    faq: [{ q: "Will a wind-and-watertight container stay dry inside?", a: "It should resist normal external weather, but internal condensation can still occur when humidity and temperature change." }, { q: "Should I insulate it?", a: "Insulation can reduce temperature swings, but it must be paired with a complete vapor, ventilation and fire-safety plan." }],
  },
  {
    slug: "container-inspection-maintenance",
    title: "Construction Container Inspection and Maintenance",
    navTitle: "Inspection and maintenance",
    category: "operations",
    description: "A repeatable inspection for doors, roof, gaskets, supports, drainage, security and interior housekeeping.",
    quickAnswer: "Set the inspection interval from the site risk assessment, supplier instructions and applicable rules. Weekly is a practical internal baseline on many active sites, not a universal legal interval. Reinspect after relocation, severe weather, impact or ground disturbance.",
    fieldNotes: ["Door binding is often an early sign that support has shifted.", "Look along the roof from a safe external vantage point. Do not climb without an approved access and fall-protection plan.", "Rust at a scrape is easier to treat before it reaches a seam or lower rail.", "Inspection findings need an owner and due date. A photo alone does not correct the condition."],
    checklist: ["Check corner supports and level", "Operate both doors", "Inspect rods, cams and hinges", "Check gaskets and lockbox", "Look for daylight or water marks", "Clear roof drainage area", "Check vents and electrical", "Clear aisle and fire access", "Record repair owner"],
    mistakes: ["Inspecting only after a leak", "Forcing binding doors", "Walking on the roof casually", "Painting over active corrosion without preparation"],
    faq: [{ q: "How often should it be inspected?", a: "Use a documented risk-based interval. Weekly is a practical internal baseline on many active sites, not a fixed universal requirement. Reinspect after relocation, severe weather, impact or ground disturbance." }, { q: "What if the doors become hard to close?", a: "Stop forcing them and keep clear of the door path. Check level, support and hardware alignment, and stop use if instability or structural damage is suspected." }],
  },
  {
    slug: "construction-container-permits",
    title: "Construction Container Permits and Local Placement Rules",
    navTitle: "Permit guide",
    category: "regulations",
    description: "A practical approval path for temporary storage containers without pretending one national rule covers every jurisdiction.",
    quickAnswer: "Check the authority having jurisdiction, property owner, fire authority and project documents before delivery. Rules can depend on duration, setbacks, visibility, anchoring, utilities, occupancy and whether the container is modified.",
    fieldNotes: ["A permit exemption for temporary construction equipment may still carry fire-lane, right-of-way or screening conditions.", "Adding power, windows, personnel doors or occupied use can change how the unit is classified.", "HOA rules are rarely the main issue on commercial jobsites, but owner and development covenants can be.", "Keep written approval with the site logistics plan so a field team can answer an inspector quickly."],
    checklist: ["Identify authority having jurisdiction", "Confirm property-owner approval", "Check zoning and temporary-use rules", "Check fire and emergency access", "Check setbacks and right-of-way", "Disclose modifications and utilities", "Confirm anchoring requirements", "Save written approval"],
    mistakes: ["Relying on a rule from another city", "Calling storage non-occupied after adding a workstation", "Ignoring fire-department access", "Ordering before confirming how long temporary placement is allowed"],
    faq: [{ q: "Do all construction containers need permits?", a: "No universal answer exists. Some jurisdictions exempt limited temporary construction storage, while permanent, modified, occupied or utility-served installations can trigger zoning, building, fire or right-of-way review." }, { q: "Who should make the call?", a: "The contractor or property owner should confirm with the local authority having jurisdiction before delivery and involve a registered design professional when structure, foundation or occupancy requires one." }],
    sources: [{ label: "ICC container code guidance", href: "https://codes.iccsafe.org/content/ICCG52019/current-code-requirements" }, { label: "2024 IBC special construction", href: "https://codes.iccsafe.org/content/IBC2024V1.0/chapter-31-special-construction" }],
  },
  {
    slug: "osha-fire-insurance-container-storage",
    title: "OSHA, Fire and Insurance Considerations for Container Storage",
    navTitle: "OSHA, fire and insurance",
    category: "regulations",
    description: "Connect container operations to material storage, egress, fire prevention, electrical and insurance controls.",
    quickAnswer: "Treat the container as part of the site safety system. Keep aisles and exits clear, secure stored materials, segregate incompatibles, control ignition sources and use compliant electrical work. A closed general-storage container is not automatically suitable for fuel, chemicals or compressed gases.",
    fieldNotes: ["OSHA 1926.250 requires stored material to be secured against sliding or collapse and aisles to remain clear.", "OSHA 1926.34 requires unobstructed egress where a structure is occupied.", "OSHA 1926.151 addresses fire prevention, combustible accumulation and indoor storage access.", "Flammable liquids and compressed gases require specific controls that go beyond general tool storage."],
    checklist: ["Maintain clear aisle and exit", "Secure stacked material", "Segregate incompatible materials", "Control combustibles and ignition", "Provide suitable extinguishers", "Use compliant electrical systems", "Review hazardous material rules", "Confirm insurance schedule and security requirements"],
    mistakes: ["Storing fuel with chargers and hot work equipment", "Locking an occupied person inside", "Blocking extinguisher access", "Assuming the property policy automatically covers every tool and container"],
    faq: [{ q: "Does OSHA have one shipping-container rule?", a: "No single rule covers every use. Applicable requirements come from material storage, egress, fire, electrical, hazardous materials and the actual work being performed." }, { q: "Can workers use the container as a break room?", a: "Only when the unit is purpose-designed and approved for occupancy. Egress must remain unobstructed and must not permit workers to be locked inside; ventilation, electrical, fire and local-code requirements may also apply." }],
    sources: [{ label: "OSHA 1926.250 material storage", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.250" }, { label: "OSHA 1926.34 means of egress", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.34" }, { label: "OSHA 1926.151 fire prevention", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.151" }, { label: "OSHA 1926.152 flammable liquids", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.152" }, { label: "OSHA 1926.350 compressed gases", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.350" }],
  },
  {
    slug: "commercial-residential-builder-storage",
    title: "Container Storage for Commercial and Residential Builders",
    navTitle: "Builders",
    category: "use-cases",
    description: "Adapt container size, placement and organization to infill homes, multifamily work and large commercial projects.",
    quickAnswer: "Residential builders usually benefit from a compact 20FT unit close to the active house. Commercial teams often use 40FT containers with trade zones, controlled access and a relocation plan tied to site phases.",
    fieldNotes: ["Residential sites are constrained by neighbors, driveways, mud control and deliveries from the street.", "Commercial sites gain value from separating general tools, finish material and controlled equipment.", "On multifamily work, moving one container by phase can be better than keeping it at the original laydown yard.", "Client-facing sites may justify cleaner exterior condition and planned screening."],
    checklist: ["Match size to site access", "Map phase-one and phase-two placement", "Define access group", "Plan trade zones", "Protect finish material", "Coordinate with delivery calendar", "Set relocation trigger"],
    mistakes: ["Using a 40FT unit on a site that cannot receive it", "Storing finish material with wet rough-work tools", "Letting every trade use the same unmarked floor", "Ignoring neighborhood or owner appearance requirements"],
    faq: [{ q: "What size suits a single-home project?", a: "A 20FT container is often easier to place and can support a disciplined small crew, but actual needs depend on equipment and access." }, { q: "How many units does a large project need?", a: "Base it on work fronts, trades, project phase and access rather than total contract value." }],
  },
  {
    slug: "specialty-trade-container-storage",
    title: "Container Storage for Electrical, Plumbing, Roofing and Concrete Trades",
    navTitle: "Specialty trades",
    category: "use-cases",
    description: "Organize a container around the retrieval patterns and material risks of specific construction trades.",
    quickAnswer: "The container should reflect the trade: electricians need secure test-equipment and conduit zones, plumbers need fitting control and dry tool storage, roofers need safe material handling, and concrete crews need separation for forms, small equipment and chemicals.",
    fieldNotes: ["Electrical: lock test gear separately and keep cable reels from consuming the aisle.", "Plumbing: use visible bins for fittings and isolate wet or contaminated equipment.", "Roofing: do not treat a closed general-storage container as approved adhesive, flammable-liquid or cylinder storage. Follow each safety data sheet and applicable fire and gas rules.", "Concrete: remove nails from used lumber before stacking and verify concentrated floor loads before storing dense equipment."],
    checklist: ["Map the top ten issued items", "Separate high-value equipment", "Separate incompatible material", "Provide long-stock storage", "Post shelf load limits", "Create reorder visibility", "Audit returns weekly"],
    mistakes: ["Using identical shelving for every trade", "Storing cylinders or flammables as ordinary supplies", "Blocking the aisle with cable or pipe", "Allowing wet equipment to create condensation"],
    faq: [{ q: "Should each trade get its own container?", a: "On large sites, dedicated units can improve accountability. On smaller sites, clearly separated zones and access rules may be enough." }, { q: "Can chemicals be stored inside?", a: "Only when each safety data sheet and applicable fire, ventilation, quantity, separation, containment and environmental rule allows the specific setup. A standard closed container is not automatically approved hazardous-material storage." }],
    sources: [{ label: "OSHA 1926.152 flammable liquids", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.152" }, { label: "OSHA 1926.350 compressed gases", href: "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.350" }],
  },
  {
    slug: "infrastructure-project-container-storage",
    title: "Container Storage for Road, Bridge and Utility Projects",
    navTitle: "Infrastructure projects",
    category: "use-cases",
    description: "Plan mobile, remote and phase-based storage for linear construction projects with changing work fronts.",
    quickAnswer: "Infrastructure projects need a relocation plan as much as a storage plan. Use containers as controlled field depots near stable access points, then move them when travel time exceeds the benefit of centralization.",
    fieldNotes: ["Road projects need clear separation from live traffic and approved barrier plans.", "Bridge work may have tight crane, floodplain and environmental constraints.", "Utility crews benefit from standardized bin layouts so stock counts stay consistent after relocation.", "Remote sites need a firm all-weather carrier route and a plan for communications, cameras and power."],
    checklist: ["Choose stable access point", "Check traffic control plan", "Check flood and drainage exposure", "Map work-front movement", "Standardize interior layout", "Plan carrier and lifting scope", "Secure remote power and communications", "Document relocation condition"],
    mistakes: ["Placing inside future excavation limits", "Treating a shoulder as a delivery pad without approval", "Moving a loaded container without written carrier approval of weight and securement", "Losing inventory control during relocation"],
    faq: [{ q: "How often should a field depot move?", a: "Move it when travel, security or access costs exceed the disruption and transport cost. Tie the decision to the look-ahead schedule." }, { q: "Can it be placed in a flood-prone area?", a: "Flood exposure requires local approval and professional review of anchoring, buoyancy, access and environmental consequences." }],
  },
  {
    slug: "construction-container-delivered-cost",
    title: "What Does a Construction Storage Container Cost?",
    navTitle: "Delivered cost guide",
    category: "costs",
    description: "Understand the components behind a delivered quote, including size, condition, inventory location, transport and modifications.",
    quickAnswer: "The useful number is the delivered total to the actual ZIP. Container size and condition set the base, while depot distance, route, site access and modifications can materially change the final price.",
    fieldNotes: ["A lower depot price can become a higher delivered price when inventory is farther away.", "Ask whether tax, permits, crane service, difficult access or waiting time are included.", "One-trip condition and custom modifications carry premiums that should solve a defined project need.", "UCD currently shows starting delivered prices on its commercial page, but final pricing depends on local inventory and delivery ZIP."],
    checklist: ["Choose size and condition", "Provide exact delivery ZIP", "Describe access and surface", "List modifications", "Request delivered total", "Clarify tax and special handling", "Confirm lead time and quote validity", "Compare equal scopes"],
    mistakes: ["Comparing depot pickup with delivered pricing", "Leaving condition grade undefined", "Pricing a crane before confirming tilt-bed access", "Using an old quote after inventory location changes"],
    table: { headers: ["Cost component", "Main driver", "How to control it"], rows: [["Container", "Size and condition", "Match grade to use"], ["Delivery", "Distance and equipment", "Use nearest suitable inventory"], ["Site", "Access complexity", "Prepare route and pad"], ["Modification", "Labor and components", "Specify only needed features"]] },
    faq: [{ q: "Why is ZIP code required?", a: "Delivery distance and available depot inventory are major parts of the delivered price." }, { q: "Are starting prices guaranteed?", a: "No. Final price depends on condition, inventory, destination and delivery requirements. Use a current written quote." }],
  },
  {
    slug: "construction-container-total-cost-ownership",
    title: "Construction Container Total Cost of Ownership and ROI",
    navTitle: "Ownership and ROI",
    category: "costs",
    description: "Model purchase, delivery, modifications, moves, maintenance and resale against rental alternatives.",
    quickAnswer: "Total ownership cost equals acquisition plus delivery, modifications, moves, maintenance and storage between projects, minus conservative resale value. Compare that with rental plus every delivery, pickup and recurring charge over the same period.",
    fieldNotes: ["Use a conservative resale number and a realistic holding period.", "Include the internal cost of arranging moves and maintaining access between projects.", "Account for saved off-site trips, reduced handling and avoided rental administration only when the project can reasonably document them.", "A container can be financially positive but operationally wrong if there is nowhere to store it after demobilization."],
    checklist: ["Set analysis period", "Enter delivered purchase price", "Add modifications", "Add planned moves", "Add maintenance and storage", "Estimate conservative resale", "Calculate equivalent rental total", "Run low, base and high scenarios"],
    mistakes: ["Counting full purchase price as permanent cost", "Ignoring between-project storage", "Using optimistic resale", "Treating avoided theft as guaranteed savings"],
    table: { headers: ["Scenario", "Ownership signal", "Rental signal"], rows: [["One short project", "Weak", "Strong"], ["Several awarded projects", "Strong", "Moderate"], ["Heavy modifications", "Strong if reusable", "Often restricted"], ["No demobilization plan", "Weak", "Strong"]] },
    faq: [{ q: "Is ROI only about rent avoided?", a: "No. It can also include transport, handling and productivity effects, but only use savings that can be supported by project data." }, { q: "Should resale be included?", a: "Yes, conservatively. Condition, market, location and transport all affect eventual value." }],
  },
  {
    slug: "construction-container-faq",
    title: "Construction Storage Container FAQ",
    navTitle: "Complete contractor FAQ",
    category: "faq",
    description: "Straight answers on size, delivery, condition, security, loading, power, permits, relocation and buying.",
    quickAnswer: "Most contractor decisions come down to five items: what must fit, where the container can sit, whether the truck can reach it, how long the project needs it and who will control access.",
    fieldNotes: ["A 20FT unit is often easier to place; a 40FT unit usually provides better capacity value.", "Wind-and-watertight describes stationary weather protection, not cosmetic appearance, transport certification or hazardous-material suitability.", "Delivered price depends on the destination ZIP and local inventory.", "Contracts and law determine duties. The carrier controls unloading until release; the site team must then assign operational ownership without assuming that assignment transfers legal responsibilities."],
    checklist: ["Define contents", "Choose size", "Choose condition", "Confirm placement approval", "Verify delivery route", "Plan supports and drainage", "Plan lock and access", "Request delivered quote", "Inspect before loading"],
    mistakes: ["Ordering before access review", "Assuming a photo is the exact unit", "Loading without an aisle", "Treating storage as occupied workspace", "Moving loaded without carrier approval"],
    faq: [{ q: "How fast can a container be delivered?", a: "UCD commonly targets 5 to 10 days after inventory, quote and access are confirmed, but the written quote and scheduling confirmation control." }, { q: "Can the driver place it exactly where I mark?", a: "Only when the route, surface, truck geometry and safety conditions allow. The carrier controls the unload and may refuse or change unsafe placement." }, { q: "Can I add shelving and lights?", a: "Yes, through a qualified structural modification and electrical plan with required permits and inspection." }, { q: "Will it keep tools dry?", a: "A sound wind-and-watertight unit should resist normal external weather. Moisture control is still needed for condensation and wet contents." }, { q: "Can it be moved later?", a: "Yes, with a qualified carrier and suitable access. Never assume it can move loaded; obtain written carrier approval for the actual weight, distribution and securement." }],
  },
  {
    slug: "small-builder-20ft-container-field-plan",
    title: "Field Plan: A 20FT Container for a Small Residential Builder",
    navTitle: "Small builder field plan",
    category: "field-scenarios",
    description: "A worked storage plan for a builder managing one or two homes on constrained residential lots.",
    quickAnswer: "Use a 20FT unit when placement and neighborhood access matter more than maximum capacity. Reserve one wall for shelving, one end for long tools and the center for a clear retrieval aisle.",
    fieldNotes: ["Place the unit beside the active work area without taking the only concrete-truck or dumpster route.", "Assign one end rack to rough-work tools and the other to protected finish equipment.", "Keep homeowner selections and delicate fixtures off the floor and away from wet tools.", "Recheck placement before grading, driveway and landscape phases change access."],
    checklist: ["Confirm driveway and street approach", "Mark a 20FT footprint", "Approve bearing system for unit, load and soil", "Install rated shelving", "Create finish-material zone", "Assign key owner", "Set phase relocation date"],
    mistakes: ["Blocking the next trade delivery", "Using floor piles instead of shelving", "Mixing wet rough-work gear with finish items", "Waiting until driveway work to plan removal"],
    table: { headers: ["Zone", "Typical contents", "Control"], rows: [["Door zone", "Daily tools", "Fast issue and return"], ["Wall racks", "Cases and consumables", "Labels by trade"], ["End zone", "Long tools", "Secured vertical rack"], ["Upper shelf", "Finish items", "Dry protected bins"]] },
    faq: [{ q: "Why not use a 40FT unit?", a: "A larger unit can be valuable, but many residential sites cannot preserve the longer truck approach and footprint through every phase." }, { q: "When should the unit move?", a: "Move it before the current location conflicts with paving, utilities, final grading or owner turnover." }],
  },
  {
    slug: "commercial-multitrade-container-field-plan",
    title: "Field Plan: Container Storage for a Multi-Trade Commercial Site",
    navTitle: "Commercial site field plan",
    category: "field-scenarios",
    description: "A worked 40FT storage layout for a commercial project with several crews and controlled equipment.",
    quickAnswer: "Use a 40FT unit as a small controlled warehouse, not a shared dumping area. Divide it into issue, trade, long-stock and high-value zones with one accountable storage lead.",
    fieldNotes: ["Put frequently issued items nearest the doors and high-value test equipment deeper inside a controlled cage or cabinet.", "Give each trade a visible zone with a maximum footprint so one crew cannot consume the aisle.", "Tie weekly inventory checks to the three-week look-ahead schedule.", "Relocate only after the qualified carrier approves the access, equipment and whether the unit must be empty. Any loaded move requires written approval of gross weight, distribution and securement."],
    checklist: ["Name storage lead", "Map four internal zones", "Post shelf load limits", "Create sign-out process", "Preserve center aisle", "Review three-week look-ahead", "Schedule weekly audit", "Plan phase-two location"],
    mistakes: ["Giving every subcontractor unrestricted keys", "Allowing pallets to block the aisle", "Storing incompatible products together", "Ordering more material before checking container stock"],
    table: { headers: ["Area", "Purpose", "Owner"], rows: [["Door bay", "Daily issue", "Storage lead"], ["Trade bays", "Consumables", "Trade foremen"], ["Controlled zone", "High-value equipment", "Superintendent"], ["Long-stock rack", "Conduit and trim", "Material manager"]] },
    faq: [{ q: "Should each trade have a separate container?", a: "Only when accountability, volume or material compatibility justifies it. A well-zoned shared unit can serve a smaller commercial project." }, { q: "Is a high cube necessary?", a: "Choose it when tall equipment or safe vertical storage will use the extra height, not simply because more volume sounds useful." }],
  },
  {
    slug: "infrastructure-mobile-depot-field-plan",
    title: "Field Plan: A Relocatable Container Depot for Infrastructure Work",
    navTitle: "Mobile depot field plan",
    category: "field-scenarios",
    description: "A worked plan for road, bridge and utility crews whose work front moves during the project.",
    quickAnswer: "Choose stable all-weather access points and move the depot by schedule trigger, not by frustration. Standardize the interior so crews find the same stock location after every relocation.",
    fieldNotes: ["Locate outside excavation, barrier and future traffic-control limits.", "Measure crew travel time from the active work front every two weeks.", "Photograph shelves and count controlled stock before and after each move.", "Obtain written carrier confirmation whether the unit must be empty. Any loaded move requires approval of gross weight, distribution, securement and equipment."],
    checklist: ["Approve traffic-control location", "Check drainage and flood exposure", "Verify all-weather route", "Standardize shelf map", "Set travel-time trigger", "Book qualified carrier", "Document load before move", "Inspect after placement"],
    mistakes: ["Placing in the future work envelope", "Using an unapproved shoulder as a pad", "Moving loose or overweight contents", "Changing the layout after every move"],
    table: { headers: ["Trigger", "Keep location", "Consider moving"], rows: [["Crew travel", "Short and predictable", "Repeated lost trips"], ["Access", "Stable all-weather route", "Upcoming closure"], ["Work phase", "Depot supports next tasks", "Work front has passed"], ["Security", "Controlled and observed", "Remote blind location"]] },
    faq: [{ q: "How often should it move?", a: "There is no fixed interval. Use the look-ahead schedule, travel time, access changes and transport cost to set a project-specific trigger." }, { q: "Can a loaded unit be moved?", a: "Only when the qualified carrier approves the load, weight, securement and equipment plan." }],
  },
  {
    slug: "long-term-multiproject-ownership-field-plan",
    title: "Field Plan: Owning a Container Across Multiple Projects",
    navTitle: "Multi-project ownership plan",
    category: "field-scenarios",
    description: "A worked ownership plan covering acquisition, project moves, maintenance, between-project storage and resale.",
    quickAnswer: "Ownership works best when the company has awarded follow-on work, a place to keep the unit between jobs and a standard interior that survives relocation. Model every move and a conservative resale value before buying.",
    fieldNotes: ["Use a standard shelf and labeling package that serves several project types.", "Budget for touch-up coating, door service and minor repairs after each demobilization.", "Keep a photo condition record at delivery, every move and project closeout.", "Do not rely on future work that is only in the bid pipeline."],
    checklist: ["List awarded projects", "Map planned moves", "Price between-project storage", "Standardize modifications", "Budget maintenance", "Set condition inspection", "Estimate conservative resale", "Compare equivalent rental"],
    mistakes: ["Counting unawarded work as certain use", "Ignoring storage between projects", "Over-customizing for one superintendent", "Using optimistic resale assumptions"],
    table: { headers: ["Cost", "Ownership model", "Evidence"], rows: [["Purchase", "Delivered total", "Written quote"], ["Moves", "Every planned transfer", "Carrier pricing"], ["Maintenance", "Annual allowance", "Inspection history"], ["Resale", "Conservative credit", "Local market range"]] },
    faq: [{ q: "How many projects justify buying?", a: "Project count alone is not enough. Compare the full rental and ownership cash flows across an evidence-based holding period." }, { q: "What modification travels best?", a: "Durable shelving, lighting and lock protection usually transfer better than a layout designed around one narrow use." }],
  },
  {
    slug: "temporary-project-rent-buy-field-plan",
    title: "Field Plan: Rent or Buy for a Temporary Construction Project",
    navTitle: "Temporary project field plan",
    category: "field-scenarios",
    description: "A decision framework for a short project with uncertain extensions, limited modifications and a fixed demobilization date.",
    quickAnswer: "Start with rental when the project is short, the end date is credible and there is no next use. Price ownership when extensions, required modifications or follow-on work could make recurring rent and transport more expensive.",
    fieldNotes: ["Use the contract schedule plus a realistic extension allowance, not the optimistic completion date.", "Include delivery, pickup, minimum rental periods and damage terms in the rental total.", "Include resale effort and removal timing in the ownership case.", "Set a decision date before rental extensions accumulate without review."],
    checklist: ["Set base duration", "Add extension scenario", "Price rental delivery and pickup", "Price delivered purchase", "List required modifications", "Confirm next-use probability", "Set review date", "Document demobilization plan"],
    mistakes: ["Comparing monthly rent with purchase price alone", "Ignoring pickup and extension charges", "Buying without a removal plan", "Assuming a schedule never slips"],
    table: { headers: ["Factor", "Rental usually fits", "Buying may fit"], rows: [["Duration", "Short and fixed", "Long or likely extended"], ["Modifications", "Minimal", "Reusable custom setup"], ["Next project", "None identified", "Awarded follow-on work"], ["Storage after", "Unavailable", "Controlled yard available"]] },
    faq: [{ q: "When should the comparison be rerun?", a: "Review it at award, before ordering and before any meaningful rental extension." }, { q: "Does buying eliminate transport cost?", a: "No. Ownership still includes initial delivery, future moves and eventual removal or resale transport." }],
  },
];

export const guideBySlug = Object.fromEntries(guides.map((guide) => [guide.slug, guide]));

export function relatedGuides(current: KnowledgeGuide, limit = 4) {
  const sameCategory = guides.filter((guide) => guide.category === current.category && guide.slug !== current.slug);
  const adjacent = guides.filter((guide) => guide.category !== current.category && guide.slug !== current.slug);
  return [...sameCategory, ...adjacent].slice(0, limit);
}
