import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { knowledgeConfig, knowledgeKeys } from "../../../knowledge/data";
import { KnowledgeFooter, KnowledgeHeader, KnowledgeMobileBar } from "../../../knowledge/KnowledgeSiteShell";

export function generateStaticParams(){return knowledgeKeys.map((vertical)=>({vertical}));}
export async function generateMetadata({params}:{params:Promise<{vertical:string}>}):Promise<Metadata>{const{vertical}=await params;const config=knowledgeConfig(vertical);if(!config)return{};return{title:`${config.name} Container Planning Brief`,description:`Source-backed container dimension graphics and a decision matrix for ${config.context}.`};}
export default async function PlanningBrief({params}:{params:Promise<{vertical:string}>}){const{vertical}=await params;const config=knowledgeConfig(vertical);if(!config)notFound();return <main className="resource-page planning-brief-page"><KnowledgeHeader config={config}/><div className="guide-topbar"><div className="wrap"><Link href={`/${config.key}`}>{config.name} containers</Link><span>/</span><Link href={`/${config.key}/resources`}>Resource center</Link><span>/</span><b>Planning brief</b></div></div><header className="planner-hero"><div className="wrap"><span className="eyebrow">Source-backed visual brief</span><h1>Correct proportions first. Exact-unit verification next.</h1><p>These charts use nominal container size to explain the comparison. They do not replace the data plate, exact-unit measurements, carrier review or site approval.</p></div></header><section className="section"><div className="wrap planning-chart-grid">
    <figure className="planning-chart"><figcaption><span>01</span><div><h2>Nominal floor area doubles from 20FT to 40FT.</h2><p>Both use the common nominal 8FT exterior width for this simple footprint comparison.</p></div></figcaption><svg viewBox="0 0 760 360" role="img" aria-label="20 foot 160 square foot and 40 foot 320 square foot nominal floor area"><rect width="760" height="360" fill="#f4f1ea"/><rect x="90" y="90" width="220" height="112" fill="#34495b"/><rect x="90" y="236" width="440" height="112" fill="#ef6b2e"/><text x="110" y="126" fill="white" fontWeight="900" fontSize="19">20FT STANDARD</text><text x="110" y="160" fill="white" fontWeight="900" fontSize="30">160 SQ FT</text><text x="110" y="272" fill="white" fontWeight="900" fontSize="19">40FT STANDARD</text><text x="110" y="306" fill="white" fontWeight="900" fontSize="30">320 SQ FT</text><path d="M90 65h440" stroke="#081421" strokeWidth="4" strokeDasharray="8 8"/><text x="540" y="70" fill="#081421" fontWeight="900" fontSize="13">2X NOMINAL LENGTH</text></svg><small>Nominal exterior footprint: 20FT × 8FT and 40FT × 8FT. Exact interior dimensions vary.</small></figure>
    <figure className="planning-chart"><figcaption><span>02</span><div><h2>High Cube adds one nominal exterior foot.</h2><p>The graphic uses the true 8.5-to-9.5 height ratio, not equal-height boxes.</p></div></figcaption><svg viewBox="0 0 760 360" role="img" aria-label="Standard 8 foot 6 inch and High Cube 9 foot 6 inch exterior height comparison"><rect width="760" height="360" fill="#f4f1ea"/><rect x="110" y="136" width="210" height="170" fill="#34495b"/><rect x="440" y="116" width="210" height="190" fill="#ef6b2e"/><path d="M85 136h260M415 116h260" stroke="#081421" strokeWidth="4"/><text x="215" y="210" textAnchor="middle" fill="white" fontWeight="900" fontSize="21">STANDARD</text><text x="215" y="245" textAnchor="middle" fill="white" fontWeight="900" fontSize="31">8FT 6IN</text><text x="545" y="200" textAnchor="middle" fill="white" fontWeight="900" fontSize="21">HIGH CUBE</text><text x="545" y="235" textAnchor="middle" fill="white" fontWeight="900" fontSize="31">9FT 6IN</text><path d="M360 136v-20h40v20M380 116V96" stroke="#2d6b49" strokeWidth="7"/><text x="380" y="78" textAnchor="middle" fill="#2d6b49" fontWeight="900" fontSize="18">+12 IN</text></svg><small>Nominal exterior heights. Verify interior and door opening dimensions on the exact unit.</small></figure>
    <article className="planning-matrix"><span className="eyebrow dark">03 | The four-gate decision</span><h2>A container is not selected by volume alone.</h2><div>{[["Contents","Dimensions, weight, sensitivity and compatibility"],["Site","Route, ground, drainage and working clearance"],["Operation","Retrieval, aisle, inspection and security routine"],["Approval","Property, carrier, authority and qualified design"]].map(([title,text],index)=><section key={title}><b>0{index+1}</b><div><h3>{title}</h3><p>{text}</p></div></section>)}</div></article>
    <article className="planning-matrix"><span className="eyebrow dark">04 | {config.name} verification</span><h2>Five checks that general content cannot close.</h2><div>{config.safetyGates.map(([title,text],index)=><section key={title}><b>0{index+1}</b><div><h3>{title}</h3><p>{text}</p></div></section>)}</div></article>
  </div></section><section className="source-notes"><div className="wrap"><span className="eyebrow dark">Sources and limits</span><h2>Every number is traceable. Every limit is visible.</h2><ul>{config.sources.map((source)=><li key={source.href}><a href={source.href} target="_blank" rel="noreferrer">{source.label} ↗</a></li>)}</ul><p>Container specifications vary by manufacturer, type and unit. Use these values only for early comparison and verify the exact container before purchase, loading or modification.</p></div></section><section className="resource-conversion-cta"><div className="wrap"><div><span className="eyebrow">Use the comparison</span><h2>Get both likely sizes priced to your ZIP.</h2><p>A specialist will match local inventory and confirm the exact unit before you commit.</p></div><div><Link className="button primary" href={`/${config.key}?quote=1#quote-form`}>Get my delivered price</Link><Link href={`/${config.key}/planner`}>Compare sizes visually</Link></div></div></section><KnowledgeFooter config={config}/><KnowledgeMobileBar config={config}/></main>;}
